// ------------------------------------
/**
 * ChatWindow
 * (c) 2010 Ian Chan <http://chanian.com>
 * MIT license
 *
 * A DM chat window conversation.
 * Holds all the individual conversation
 * data, and couples itself with a DOM view elements.
 * This contains the view as well.
 *
 */
// ------------------------------------
var chatwindow = function(user, parentObj, id) {
	var that = {};
	
	// What is the twitter username of the person
	that.user = user;
	
	// What is my global ID
	that.id = id;		

	// Is this window open?
	that.isOpen = false;
	
	// Create a new dom element during constructor
	that.view = document.createElement('div');
	parentObj.appendChild(that.view);

	// ----------------------------------------		
	// Prep a new DM, push it out, and render it
	that.sendDM = function() {
		// Recover the form data
		var obj = document.getElementById("f" + this.id);
		var msg = obj.value;
		
		// Clear that input field
		obj.value = "";		
				
		// Construct a new DM to send out
		if(msg.length > 0) {		
			var dm = {};
			dm.user = this.user;
			dm.text = msg;
			
			// Message the kernal, and render what we get back!
			DMChat.sendDM(dm, "renderDM", this);
		}
	}	
	// ----------------------------------------			
	// Take a dm object and render it to the screen
	that.renderDM = function(dm) {
		var className = 'message';

		// Did I say this?
		if(dm.is_owner) {
			className = 'message message-owner';
		}
		
		// Make the date a bit more readable
		var date_string = dateFormat((new Date(dm.created_at)), "d/m/yy, h:MMtt");
		
		// build the dom element (should be templated)
		var html = "<div class='" + className + "'>"+
						"<div class='author'>@" + dm.user +  " says: </div>"+
						"<div class='date'>(" + date_string + ")</div>"+						
						"<div class='text'>" + dm.text + "</div>" +
					"</div>";	
 		$( document.getElementById("c" + this.id) ).prepend(html);		
	}
	// ----------------------------------------			
	// Close up the window
	that.close = function() {
		$( this.view ).fadeOut("fast");		
		this.isOpen = false;
	}
	
	// ----------------------------------------			
	// Bootstrap and setup a chat window.
	// Fetch content and couple the content with 
	// a view container.
	var init = function() {
		// Hide it for now so we can inimate it in
		$( that.view ).hide();
		
		// Should be templated (hangs head in shame)
		that.view.innerHTML = getView(that.id, that.user);

		// Hydrate with most recent DM's
		var dms = DMChat.buildConversation(user);

		// render them backwards, for reverse chron order		
		for(var i = dms.length - 1; i >= 0; i--) {
			that.renderDM(dms[i]);
		}	
		
		// Add window behaviour here
		$( that.view ).fadeIn();
		$( that.view ).draggable( { handle:"div.dmHeader" } );		
		that.isOpen = true;		
		
		// Bring it to the top now, and upon click
		$( that.view ).mousedown(function() {
			DMChat.WM.setFocus(that);		
		});
		// Bring it to the front
		$( that.view ).trigger('mousedown');		
	};
	
	// ----------------------------------------				
	// Prepare and return view code in HTML form:
	// Render a default window shell (could also use templating)	
	// Note, I've always had a philisophical debate whether views
	// should be in JS, templated, autogenerated from server etc.
	// Generally I don't like coupling JS with CSS classnames and DOM
	// but I need the view now, and the guy beside me on the plane 
	// isn't giving me much elbow room...
	var getView = function() {
		return "<div class='dmWindow' id='w" + id + "'>" +
			"<div class='dmBorder'>" +
				"<div class='dmContent'>" +
					"<div class='dmPart dmHeader' id='header" + id + "'>"+
						"<div class='label'>Chat Window with @" + user + "</div>"+
						"<div class='close' onclick='DMChat.WM.close(" + id + ");'>X</div>" +
					"</div>"+
					"<div class='dmPart dmProfile'></div>"+
					"<div class='dmPart dmBody'>"+
						"<div class='conversation' id='c" + id + "'></div>"+
					"</div>"+
					"<div class='dmPart dmFooter'>"+
						"<div><textarea id='f" + id + "'></textarea></div>"+
						"<div>"+
							"<div class='dmFooterCounter'></div>"+
							"<input value='Say!' type='button' " +
							"onclick='DMChat.WM.windows[" + id + "].sendDM();'></input>"+
						"</div>"+
					"</div>"+
				"</div>"+
			"</div>"+
		"</div>";
	}	
	
	// Bootstrap and return
	init();
	return that;
}
